services:
  - type: web
    name: nexus-be
    runtime: node
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: APP_BASE_URL
        sync: false
